/* Blocked words: every variant below is an explicit whole-word entry.
   No runtime letter-by-letter substitution is used. */
(function(){
  'use strict';
  window.BLOCKED_WORDS = [
    'l systeem',
    'lsystaem',
    'lsysteeem',
    'slysteem',
    'lsyseem',
    'kut systeem',
    'kutsystaem',
    'kutsysteeem',
    'koetsysteem',
    'kuutsysteem',
    'uktsysteem',
    'kutsyteem',
    'kut',
    'kutt',
    'kud',
    'kuttt',
    'koet',
    'kuut',
    'kanker',
    'kancer',
    'canker',
    'cancer',
    'kankar',
    'kankor',
    'kankur',
    'kankerr',
    'kancerr',
    'cankerr',
    'kankerh',
    'kenker',
    'kaanker',
    'kankeer',
    'aknker',
    'kaner',
    'mongool',
    'mongol',
    'mongooll',
    'mongoul',
    'moongool',
    'mungool',
    'omngool',
    'monool',
    'loser',
    'looser',
    'lozar',
    'losor',
    'lozer',
    'loserr',
    'losar',
    'loseer',
    'luser',
    'olser',
    'loer',
    'kut lars',
    'kutlers',
    'kutlaars',
    'koetlars',
    'kuutlars',
    'uktlars',
    'kutars',
    'l lars',
    'llers',
    'llaars',
    'lalrs',
    'llrs',
    'fuck',
    'fuk',
    'fock',
    'fukk',
    'fucc',
    'fuc',
    'fukkk',
    'foeck',
    'fuuck',
    'ufck',
    'gay',
    'gaay',
    'gai',
    'gey',
    'gei',
    'gayy',
    'hoer',
    'hoerh',
    'hoeer',
    'huur',
    'hoor',
    'hoar',
    'hooer',
    'huer',
    'oher',
    'hor',
    'neuken',
    'neuke',
    'nueken',
    'neukke',
    'neukenn',
    'nauken',
    'neeuken',
    'neoeken',
    'neuuken',
    'enuken',
    'neuen',
    'raggen',
    'ragge',
    'raggenn',
    'ragggen',
    'reggen',
    'raaggen',
    'raggan',
    'raggeen',
    'arggen',
    'ragen',
    'verkrachten',
    'verkrachte',
    'verkraghten',
    'verkr8ten',
    'verkrachtte',
    'verkrachtten',
    'verkrechten',
    'verkraachten',
    'varkrachten',
    'veerkrachten',
    'evrkrachten',
    'verkrachten',
    'seksen',
    'sexen',
    'seksenn',
    'sekssen',
    'saksen',
    'seeksen',
    'esksen',
    'seken',
    'sex',
    'seks',
    'sexx',
    'sexs',
    's3x',
    'segs',
    'sax',
    'seex',
    'opgekankerd',
    'opgekancerd',
    'opgecankerd',
    'opgekankert',
    'opgekankerdd',
    'opgekanckerd',
    'opgekenkerd',
    'opgekaankerd',
    'opgakankerd',
    'opgeekankerd',
    'oopgekankerd',
    'upgekankerd',
    'pogekankerd',
    'opgeknkerd',
    'nigger',
    'niger',
    'nigerr',
    'niggerr',
    'niggar',
    'niggr',
    'niggeer',
    'nygger',
    'niegger',
    'ingger',
    'nigga',
    'niga',
    'niggaa',
    'niggaah',
    'nigge',
    'nygga',
    'niegga',
    'ingga',
    'aftrekken',
    'aftrekke',
    'aftreken',
    'aftrekkken',
    'aftrekk',
    'aftrecken',
    'eftrekken',
    'aaftrekken',
    'aftrakken',
    'aftreekken',
    'fatrekken',
    'aftrkken',
    'masturberen',
    'masturbere',
    'masturbeeren',
    'masturbren',
    'mesturberen',
    'maasturberen',
    'masturbaren',
    'mastoerberen',
    'mastuurberen',
    'amsturberen',
    'mastuberen',
    'kkr',
    'kkrr',
    'kkrh',
    'lul',
    'lull',
    'lulll',
    'loel',
    'luul',
    'piemel',
    'piemell',
    'piemal',
    'piemil',
    'piemmel',
    'pimel',
    'piamel',
    'pieemel',
    'pyemel',
    'ipemel',
    'pieel',
    'pimell',
    'pimml',
    'pimal',
    'pimeel',
    'pymel',
    'ipmel',
    'piel',
    'plassertje',
    'plassertjee',
    'plassert',
    'plaserstje',
    'plessertje',
    'plaassertje',
    'plassartje',
    'plasseertje',
    'lpassertje',
    'plassrtje',
    'comdoom',
    'condoom',
    'komdoom',
    'comdoon',
    'comdoem',
    'comdooom',
    'condom',
    'coomdoom',
    'cumdoom',
    'ocmdoom',
    'comoom',
    'vagina',
    'vaginaa',
    'vagyna',
    'vagiena',
    'vegina',
    'vaagina',
    'avgina',
    'vagna',
    'bek',
    'beq',
    'b3k',
    'bakk',
    'bekk',
    'beek',
    'bak',
    'vape',
    'vaap',
    'vappe',
    'vepe',
    'vaype',
    'vapee',
    'vaape',
    'vapa',
    'avpe',
    'vae',
    'sigaret',
    'sigarett',
    'sigeret',
    'sigaaret',
    'sigarat',
    'sigareet',
    'sygaret',
    'siegaret',
    'isgaret',
    'sigret',
    'sigaar',
    'sigar',
    'sigaarr',
    'sigaer',
    'sigear',
    'sigaaar',
    'sygaar',
    'siegaar',
    'isgaar',
    'wiet',
    'wiett',
    'wied',
    'wjeit',
    'weat',
    'wiat',
    'wieet',
    'wyet',
    'iwet',
    'wit',
    'cocaiene',
    'coccaiene',
    'cocaine',
    'cocaene',
    'cocayene',
    'coccaine',
    'coceiene',
    'cocaaiene',
    'cocaiane',
    'cocaieene',
    'coocaiene',
    'cucaiene',
    'occaiene',
    'drugs',
    'druks',
    'drux',
    'droegs',
    'druugs',
    'rdugs',
    'drgs',
    'tering',
    'taring',
    'teering',
    'teryng',
    'terieng',
    'etring',
    'terng',
    'tifus',
    'tyfus',
    'tiefus',
    'tifoes',
    'tifuus',
    'itfus',
    'tius',
    'fiefus',
    'fiafus',
    'fieefus',
    'fyefus',
    'fiefoes',
    'fiefuus',
    'ifefus',
    'fieus',
    'pijpen',
    'klootzak',
    'klootzakk',
    'klootzakke',
    'klootzakken',
    'klootzaak',
    'klootsak',
    'kloootzak',
    'klootzack',
    'pijpan',
    'pijpeen',
    'pyjpen',
    'piejpen',
    'ipjpen',
    'pijen',
  ];

  var ERROR_MESSAGE = 'Dit woord is niet toegestaan.';
  var lastAllowedValue = new WeakMap();

  function isTextField(el) {
    if (!el || el.nodeType !== 1) return false;
    if (el.tagName === 'TEXTAREA') return true;
    if (el.tagName === 'INPUT') {
      var type = (el.type || 'text').toLowerCase();
      return ['text', 'search', 'email', 'url', 'tel', 'password'].indexOf(type) !== -1;
    }
    return el.isContentEditable === true;
  }

  function cleanNormal(val) {
    return String(val || '').normalize('NFKC').toLowerCase().replace(/[\u200B-\u200D\uFEFF]/g, '');
  }

  function cleanCompact(val) {
    return cleanNormal(val).replace(/\s+/g, '');
  }

  function containsBlockedWord(value) {
    var textNormal = cleanNormal(value);
    var textCompact = cleanCompact(value);
    if (!textNormal) return null;

    for (var i = 0; i < window.BLOCKED_WORDS.length; i++) {
      var blockedOriginal = window.BLOCKED_WORDS[i];
      var blockedNormal = cleanNormal(blockedOriginal);
      var blockedCompact = cleanCompact(blockedOriginal);

      if (!blockedCompact) continue;

      // 1. Check op exact woord met grenzen in de normale tekst (bijv. "dit is kut")
      var escaped = blockedNormal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      // We gebruiken [^a-z0-9] als grenscontrole om woorden in zinnen te vangen
      var regex = new RegExp('(^|[^a-z0-9])' + escaped + '($|[^a-z0-9])', 'i');
      if (regex.test(textNormal)) return blockedOriginal;

      // 2. Check of de compacte tekst het compacte woord bevat (bijv. "k u t")
      // Alleen voor woorden >= 3 letters om valse meldingen te voorkomen.
      if (blockedCompact.length >= 3 && textCompact.indexOf(blockedCompact) !== -1) {
        return blockedOriginal;
      }
    }
    return null;
  }

  function getValue(el) { return el.isContentEditable ? el.textContent : el.value; }
  function setValue(el, val) { if (el.isContentEditable) el.textContent = val; else el.value = val; }

  function handleInput(e) {
    var el = e.target;
    if (!isTextField(el)) return;
    var val = getValue(el);
    if (containsBlockedWord(val)) {
      var prev = lastAllowedValue.get(el) || '';
      setValue(el, prev);
      alert(ERROR_MESSAGE);
    } else {
      lastAllowedValue.set(el, val);
    }
  }

  document.addEventListener('input', handleInput, true);
  document.addEventListener('focusin', function(e) {
    if (isTextField(e.target)) lastAllowedValue.set(e.target, getValue(e.target));
  }, true);

  window.containsBlockedWord = containsBlockedWord;
})();
