// German update log. Kept in sync with updates-en.js.
// This file contains a complete German copy so the update log does not depend
// on a live translation request just to display its contents.
window.UPDATES_DE = [
 {title:'Mehrere Sprachen!',date:'06-09-2026',time:'20:30',info:'Noch ein allerletztes riesiges Update: Wir haben 2 große neue Funktionen hinzugefügt. Erstens mehrere Sprachen: Du kannst Englisch oder Deutsch auswählen und alle Texte werden automatisch in die von dir gewählte Sprache übersetzt, außer den Dingen, die du selbst in deinen Restaurants einstellst. Auch die Updates im Update-Log werden in dieser Sprache angezeigt und sogar die Ankündigungen oder Verwarnungen, die ich schreibe, werden übersetzt. Wenn es Fehler in der Sprache gibt, gib sie bitte sofort über das Feedback weiter und ich werde versuchen, sie zu beheben. Mach das auch, wenn etwas nicht übersetzt wurde. Außerdem kann ich jetzt einen Grund für deine Sperre oder Auszeit angeben, damit jeder weiß, warum jemand gesperrt wurde oder eine Auszeit erhalten hat. Ich habe auch ein paar blockierte Wörter hinzugefügt und einige Fehler behoben. Ab jetzt werde ich etwas weniger Updates machen. Ich werde nicht ankündigen, wenn es an einem Tag kein Update gibt. Bis zum nächsten Update!'},
 {title:'Hintergrundmuster',date:'03-09-2026',time:'21:15',info:'Ich habe ein paar Dinge hinzugefügt. Erstens kannst du jetzt für deine Mitglieder im Restaurant einen eigenen Namen festlegen, anstatt ihren Benutzernamen anzuzeigen. Der Besitzer kann außerdem festlegen, ob ein Mitglied das Restaurant bearbeiten darf. Ich habe auch Hintergrundmuster hinzugefügt: 10 Essensmuster und einige andere Designs sowie 10 Hintergrundfarben und 5 Schriftarten. Außerdem gibt es jetzt einen zweiten Standard-Benachrichtigungston, sodass du zwischen den beiden oder deinem eigenen hochgeladenen Ton wählen kannst. Einige Fehler wurden ebenfalls behoben. Bis morgen!'},
 {title:'Mega-Update!',date:'02-09-2026',time:'20:45',info:'Dies ist ein riesiges Update mit vielen wichtigen Neuerungen. Wenn du zum ersten Mal online kommst, musst du jetzt einen Benutzernamen festlegen und kannst ihn später ändern. Wenn ich jedoch herausfinde, dass es nicht dein echter Name ist oder dein echter Name darin enthalten ist, kannst du eine Auszeit oder eine Sperre erhalten. Ich habe außerdem die Möglichkeit hinzugefügt, Personen zu sperren, Auszeiten zu vergeben und Verwarnungen auszusprechen. Eine Auszeit ist vorübergehend; eine Sperre bleibt dauerhaft bestehen, bis ich dich entsperre. Du kannst eine Beschwerde einreichen und ich kann dich wieder entsperren. Du kannst jetzt auch Nachrichten aneinander senden: Suche nach einem Benutzernamen, gib einen Titel und eine Nachricht ein und sende sie. Nachrichten sind über die Glocke verfügbar, bei der auch die Ankündigungen angezeigt werden. Schließlich habe ich weitere blockierte Wörter und verschiedene Varianten davon hinzugefügt. Morgen könnte noch ein weiteres Update kommen, aber ich bin mir noch nicht sicher. Bis morgen!'},
 {title:'Blockierte Wörter',date:'01-09-2026',time:'20:30',info:'Ich habe etwas sehr Wichtiges hinzugefügt: blockierte Wörter. Das ist nützlich, um Streit und Sperren zu vermeiden. Zu den blockierten Wörtern gehören Schimpfwörter und ähnliche Begriffe. Wenn ich solche Wörter weiterhin in veränderter Schreibweise sehe, bekommst du möglicherweise ein sehr großes Problem. Wenn du eine Beschwerde dazu hast, kontaktiere mich. Ich habe außerdem ein paar andere Dinge behoben, die du wahrscheinlich nicht bemerken wirst. Bis zum nächsten Update!'},
 {title:'Feedback- und Systemverwaltungs-Fix',date:'31-08-2026',time:'20:30',info:'Zuerst habe ich Feedback hinzugefügt. Du kannst jetzt Feedback geben, um Fehler zu melden und Ideen für das System vorzuschlagen. Ich kann dieses Feedback in der Systemverwaltung lesen. Du kannst weiterhin maximal 2 Restaurants erstellen, aber so viele Restaurants beitreten, wie du möchtest. Dies ist jetzt auch in Kategorien unterteilt. Feedback kann nur einmal alle 5 Minuten gesendet werden, damit ich nicht zugespammt werde. Das war das Update; bis morgen!'},
 {title:'Große Erweiterung des Selbstbedienungssystems!',date:'30-08-2026',time:'20:30',info:'Ich habe mehrere Änderungen hinzugefügt. Erstens sind jetzt Services verfügbar: Kunden können in der Selbstbedienung einen Service anfordern, den du in den Einstellungen erstellst. Wenn ein Service angefordert wird, erscheint er an dem Tisch, an dem er angefordert wurde, und am Tisch wird eine Zahl angezeigt. Das Personal kann dann den Tab „Services“ öffnen, die Anfragen sehen und sie als erledigt markieren. Kunden können ihre angeforderten Services und den aktuellen Status ebenfalls sehen. Außerdem kannst du bei der Selbstbedienung jetzt die Auswahl eines Tisches aufheben, als kleinen Bugfix. Ich habe auch ein Problem behoben, bei dem das automatische Löschen eines Restaurants ein neues Restaurant erstellen konnte. Das war das Update; bis zum nächsten Mal!'},
 {title:'Kleines Update',date:'29-08-2026',time:'22:00',info:'Ich habe Notizen hinzugefügt. Du kannst maximal 20 haben, sie abhaken und sie werden danach automatisch entfernt. Notizen werden mit dem gesamten Restaurant geteilt, sodass jeder sie erstellen und abhaken kann. Außerdem gibt es jetzt eine Option, ein Restaurant nach einer festgelegten Zeit automatisch zu löschen. Es gab noch einen kleinen Fehler, der aber behoben wird. Bis morgen!'},
 {title:'Mittelgroßes Update',date:'27-08-2026',time:'21:30',info:'Du kannst jetzt auswählen, ob eine Bestellung an die Küche oder an die Bar gesendet wird. Ich habe außerdem einen eigenen Bar-Tab hinzugefügt, in dem alle Bestellungen für die Bar erscheinen. Du kannst ohne Tisch bestellen, indem du auf die Bar-Option drückst. Bestellungen mit Küchen- und Bar-Artikeln werden automatisch aufgeteilt. Ich habe außerdem einige Fehler behoben, und für das nächste Update war noch ein weiterer Fix für die Zählung in der Selbstbedienung geplant.'},
 {title:'Vollständige Handy-Unterstützung',date:'27-08-2026',time:'13:00',info:'Du kannst jetzt auf deinem Handy alles richtig sehen, ohne ganz nach links oder rechts scrollen zu müssen. Ich habe außerdem einen weiteren Fehler behoben. Das nächste Update wird kleiner sein und bald veröffentlicht!'},
 {title:'Großes Update mit mehreren neuen Dingen!',date:'26-08-2026',time:'20:45',info:'Ich habe Kategorien hinzugefügt, sodass du Produkte in Kategorien aufteilen und festlegen kannst, welche Kategorie zuerst oder zuletzt erscheint. In der Historie wird jetzt auch angezeigt, wie viele Artikel aus jeder Kategorie bestellt wurden. Kategorien lassen sich beim Bearbeiten eines Produkts einfach auswählen. Außerdem habe ich Rollen hinzugefügt, sodass der Besitzer Rollen an Mitarbeiter vergeben kann und die Rolle neben dem Namen angezeigt wird. Du kannst jetzt zuvor erhaltene Verwarnungen ansehen und sehen, zu welchem Restaurant sie gehören. Die Handy-Unterstützung wurde auch für die Bestell-Grundriss hinzugefügt, die jetzt automatisch kleiner wird. Schließlich habe ich die Selbstbedienungs-Oberfläche verkleinert, damit mehr auf den Bildschirm passt. Zukünftige Updates werden kleiner sein, aber weiterhin gut!'},
 {title:'Eigenen Benachrichtigungston hochladen!',date:'25-08-2026',time:'21:15',info:'Ich habe ein paar kleine Dinge hinzugefügt. Du kannst jetzt deinen eigenen Benachrichtigungston für eingehende Bestellungen hochladen, mit maximal 1 Datei und 400 KB. Außerdem habe ich einen Ton hinzugefügt, der nach der Zahlung abgespielt wird. Ich kann jetzt eine Ankündigung posten, die ähnlich wie eine Verwarnung aussieht. Schließlich habe ich große Verbesserungen am Design vorgenommen, mit schöneren Pop-ups und einem übersichtlicheren Aussehen!'},
 {title:'Selbstbedienung und andere neue Dinge',date:'24-08-2026',time:'20:45',info:'Dies ist das größte Update, das gemacht werden wird. Es enthält ein Selbstbedienungssystem: Personen scannen einen QR-Code aus den Einstellungen, wählen einen Tisch und die Produkte mit Optionen wie Eiswürfeln. Sie können außerdem eine eigene Notiz eingeben. Die Bestellung wird an die Küche gesendet und funktioniert dort wie gewohnt. Während die Bestellung zubereitet wird, können Kunden ihren Status sehen und wie viele Bestellungen noch vor ihnen liegen. Schließlich wird die Bestellung in die Historie verschoben und die Zahlung funktioniert auf die gleiche Weise. Ich habe außerdem hinzugefügt, dass die Systemverwaltung einem Restaurant eine Verwarnung senden kann, wenn es nicht in Ordnung ist. Das Design wurde ebenfalls deutlich verbessert. Das nächste Update wird kleiner, aber genauso cool sein!'},
 {title:'Kleines Update mit einigen Verbesserungen',date:'24-08-2026',time:'11:45',info:'Du kannst jetzt die Schriftart ändern und aus 15 verschiedenen Schriftarten wählen. Ich habe außerdem die Sicherheit der Systemverwaltung verbessert. Im Update-Log wird jetzt die Veröffentlichungszeit angezeigt. Es gab außerdem einige Fehlerbehebungen. Das nächste Update wird das bisher größte sein, also schau es dir unbedingt an!'},
 {title:'Systemverwaltung und Bestand-Tab',date:'24-08-2026',time:'08:00',info:'Ich habe viele neue Dinge hinzugefügt. Du kannst jetzt die Farbe des Restaurantnamens ändern und musst dir beim Beitreten oder Erstellen eines Restaurants einen Namen geben. Du kannst ein Restaurant jetzt auch einfach über die Einstellungen verlassen. Wenn der Besitzer das Restaurant verlässt, wird das gesamte Restaurant gelöscht. Du kannst eine Bank jetzt horizontal oder vertikal drehen. Als Administrator kann ich bei Bedarf außerdem jedes Restaurant verwalten, ändern und löschen. Schließlich habe ich einen Bestand-Tab hinzugefügt, der alle Produkte zeigt. Du kannst Produkte als nicht verfügbar markieren, sodass sie nicht mehr bestellt werden können. Außerdem wurden einige Fehler behoben.'},
 {title:'Optionen und neue Möbel',date:'22-08-2026',time:'20:00',info:'Du kannst jetzt zusätzliche Optionen wie extra Soße hinzufügen und dafür ein Emoji auswählen. Es funktioniert ein wenig wie das alte Eiswürfel-System. Ich habe außerdem zusätzliche Möbel hinzugefügt: eine Bar, eine Küche und eine Bank. Tische können jetzt rund, quadratisch oder rechteckig sein. Ich habe außerdem 5 zusätzliche Hintergrundfarben hinzugefügt. Das nächste Update wird sehr groß und bald veröffentlicht!'},
 {title:'Kleines Update mit ein paar Änderungen',date:'20-08-2026',time:'21:00',info:'Ich habe 2 neue Dinge hinzugefügt. Erstens kannst du jetzt auswählen, welche Hintergrundfarbe du möchtest; du kannst aus 25 Farben wählen. Zweitens kann der Grundriss jetzt größer als 20x20 Kästchen sein. Es gab außerdem einige kleine Fehlerbehebungen. Das nächste Update wird ein sehr großes sein!'},
 {title:'Großes Update mit vielen neuen Funktionen',date:'19-08-2026',time:'20:30',info:'Du kannst jetzt deine Mitglieder verwalten und auswählen, auf welche Tabs sie zugreifen können, zum Beispiel Bestellen und Historie. Ich habe außerdem einen Update-Log hinzugefügt. Mitglieder können entfernt werden und der Beitrittscode wird automatisch aktualisiert. Bereiche können jetzt von beiden Seiten vergrößert werden. Ich habe das Design ebenfalls geändert, damit es sauberer aussieht, und mehrere weitere Fehler behoben. Das neue Update wird bald veröffentlicht!'}
];
window.UPDATES_DE_READY = true;
