// English update log. Keep this file in sync with updates.js when adding updates.
window.UPDATES_EN = [
 {title:'Multiple languages!',date:'06-09-2026',time:'20:30',info:'One final huge update: we added 2 major new features. First, multiple languages: you can choose English or German and all text will automatically be translated into the language you choose, except for the things you set yourself in your restaurants. The updates in the update log will also be shown in that language, and even the announcements or warnings I type will be translated. If there are errors in the language, let me know immediately through feedback and I will try to fix them. Do the same if something is not translated. I also added that I can now give a reason for your ban or timeout so everyone knows why someone was banned or timed out. I also added a few blocked words and fixed some bugs. From now on I will be doing fewer updates. I will not announce it when there is no update on a day; see you at the next update!'},
 {title:'Background patterns',date:'03-09-2026',time:'21:15',info:'I added a few things. First, you can now set a custom name for your members in the restaurant instead of showing their username. The owner can also decide whether a member is allowed to modify the restaurant. I also added background patterns: 10 food patterns and a few other designs, plus 10 background colors and 5 fonts. I also added a second standard notification sound, so you can choose between the two or your own uploaded sound. A few bugs were fixed as well. See you tomorrow!'},
 {title:'Mega update!',date:'02-09-2026',time:'20:45',info:'This is a huge update with many major additions. You now have to set a username the first time you come online, and you can change it later. However, if I find out that it is not your real name or that it contains your real name, you may receive a timeout or be banned. I also added the ability to ban people, give timeouts and issue warnings. A timeout is temporary; a ban is permanent until I unban you. You can submit a complaint and I may unban you. You can now also send messages to each other: search for a username, enter a title and message, and send it. Messages are available from the bell where the announcements are shown. Finally, I added more blocked words and different versions of them. There may be another update tomorrow, but I am not sure yet. See you tomorrow!'},
 {title:'Blocked words',date:'01-09-2026',time:'20:30',info:'I added something very important: blocked words. This is useful to prevent arguments and bans. The blocked words include swear words and similar terms. If I still see such words written differently, you may have a very big problem. If you have a complaint about this, contact me. I also fixed a few other things that you will not notice. See you in the next update!'},
 {title:'Feedback and system management fix',date:'31-08-2026',time:'20:30',info:'First, I added feedback. You can now give feedback to report bugs and suggest ideas for the system. I can read this feedback in site management. You can still create a maximum of 2 restaurants, but you can join as many as you want. This is now also divided into categories. Feedback can only be sent once every 5 minutes so I do not get spammed. That was the update; see you tomorrow!'},
 {title:'Big addition to the self-service system!',date:'30-08-2026',time:'20:30',info:'I added several changes. First, services are now available: customers can request a service in self-service that you create in Settings. When a service is requested, it appears at the table where it was requested, with a number shown on the table. Staff can then open the Services tab, see the requests and mark them as done. Customers can also see their requested services and their current stage. You can now deselect a table in self-service as a small bug fix. I also fixed an issue where automatically deleting a restaurant could create a new one. That was the update; see you next time!'},
 {title:'Small update',date:'29-08-2026',time:'22:00',info:'I added notes. You can have a maximum of 20, tick them off, and they are automatically removed afterwards. Notes are shared with the entire restaurant, so everyone can create and tick them off. I also added an option to automatically delete a restaurant after a set time. There was still a small bug, but that is being fixed. See you tomorrow!'},
 {title:'Medium-sized update',date:'27-08-2026',time:'21:30',info:'You can now choose whether an order is sent to the kitchen or the bar. I also added a separate Bar tab where all bar orders appear. You can order without a table by pressing the bar option. Orders containing kitchen and bar items are automatically split. I also fixed some bugs, and another self-service counting fix was planned for the next update.'},
 {title:'Full phone support',date:'27-08-2026',time:'13:00',info:'You can now see everything properly on your phone without having to scroll all the way left or right. I also fixed another bug. The next update will be smaller and will be released soon!'},
 {title:'Big update with several new things!',date:'26-08-2026',time:'20:45',info:'I added categories, so you can divide products into categories and decide which category appears first or last. History also shows how many items from each category were ordered. Categories are easy to select when editing a product. I also added roles, so the owner can assign roles to employees, and the role is shown next to the name. You can now view previously received warnings and see which restaurant they belong to. Phone support was also added to the order floor plan, which now becomes smaller automatically. Finally, I made the self-service UI smaller so more fits on screen. Future updates will be smaller but still good!'},
 {title:'Upload your own notification sound!',date:'25-08-2026',time:'21:15',info:'I added a few small things. You can now upload your own notification sound for incoming orders, with a maximum of 1 file and 400 KB. I also added a sound that plays after payment. I can now post an announcement that looks similar to a warning. Finally, I made major style improvements with nicer pop-ups and a cleaner look!'},
 {title:'Self-service and other new things',date:'24-08-2026',time:'20:45',info:'This is the biggest update that will be made. It includes a self-service system: people scan a QR code from Settings, choose a table and choose products with options such as ice cubes. They can also add a typed note. The order is sent to the kitchen, where it works normally. While the order is being prepared, customers can see its stage and how many orders are ahead of it. Eventually the order goes to history and payment works the same way. I also added the ability for system management to send a warning to a restaurant when it is not in order. The style was upgraded significantly as well. The next update will be smaller but just as cool!'},
 {title:'Small update with a few improvements',date:'24-08-2026',time:'11:45',info:'You can now change the font and choose from 15 different fonts. I also improved the security of system management. The update log now shows the release time. There were also a few bug fixes. The next update will be the biggest one yet, so make sure to check it out!'},
 {title:'System management and stock tab',date:'24-08-2026',time:'08:00',info:'I added many new things. You can now change the restaurant name color and you have to give yourself a name when joining or creating a restaurant. You can also leave a restaurant easily from Settings. If the owner leaves, the entire restaurant is deleted. You can now rotate a bench horizontally or vertically. I can also manage, modify and delete any restaurant as the administrator when needed. Finally, I added a Stock tab showing all products, where you can mark products as out of stock so they can no longer be ordered. A few bugs were fixed too.'},
 {title:'Options and new furniture',date:'22-08-2026',time:'20:00',info:'You can now add extra options such as extra sauce and choose an emoji for them. It works a bit like the old ice-cubes system. I also added extra furniture: a bar, a kitchen and a bench. Tables can now be round, square or rectangular. I also added 5 extra background colors. The next update will be very big and will be released soon!'},
 {title:'Small update with a few changes',date:'20-08-2026',time:'21:00',info:'I added 2 new things. First, you can now choose the background color from 25 colors. Second, the floor plan can now be larger than 20x20 squares. There were also a few small bug fixes. The next update will be a very big one!'},
 {title:'Big update with many new features',date:'19-08-2026',time:'20:30',info:'You can now manage your members and choose which tabs they can access, such as ordering and history. I also added an update log. Members can be kicked and the join code is automatically refreshed. Areas can now be enlarged from both sides. I also changed the style to make it cleaner and fixed several other bugs. The new update will be released soon!'}
];
